# Generated by Django 5.1.4 on 2025-01-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(related_name='orders', to='bookapp.books'),
        ),
    ]
