# Generated by Django 5.1.4 on 2025-01-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_order_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
