# Generated by Django 5.1.4 on 2025-02-08 14:39

import bookapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_alter_books_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
