# Generated by Django 5.1.4 on 2025-02-08 21:11

import bookapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_books_preview_order_receipt_alter_books_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=bookapp.models.book_preview_directory_path),
        )
    ]
